### ISSUE TITLE
Cannot use XCFramework in app extensions

### ISSUE THREAD

**Issue by justin** [OneSignal/OneSignal-XCFramework#3] opened 2021-01-26 17:14 UTC
Thank you for making an XCFramework variant of your SDK! This solves a common frustration our developers have with the SDK: the size of the Swift package download. 

I tried to look into transitioning to it this morning, but we are unable to link it safely against our notification service extension because of the following error. 

> ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/justin/Library/Developer/Xcode/DerivedData/Product-garuxyrngxvourcmnkyhgczgleqk/Build/Products/Development-iphonesimulator/OneSignal.framework/OneSignal

Would be great if this could be resolved in a future version.

Thank you!

**Comment by emawby** [comment] 2021-01-29 22:01
Hello this is a known issue documented on the [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/396), but it should not actually affect your build. The warning is caused by  OneSignal referencing UIApplication APIs when it is used from an App target. Since we don't have separate frameworks for the app target and NSE Xcode complains. However we will never call the un-allowed apis from the NSE. We are looking into a fix for this warning.

**Closed by emawby** 2021-01-29 22:01 UTC
